#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://172.16.23.122:1111/eureka/,http://172.16.23.123:1111/eureka/
spring:
  cloud:
    inetutils:
      ignored-interfaces: eth1
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.23.65:3306/org_api_test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: org_api
    password: dinglicom
    hikari:
      auto-commit: false
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 600000
      idle-timeout: 60000
      validation-timeout: 1000
      leak-detection-threshold: 30000
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: MYSQL
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming.strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
  redis:
    host: 172.16.23.117
    database: 13
    pool:
      max-active: 10
      max-idle: 10
      max-wait: 5
      min-idle: 1
  kafka:
    bootstrap-servers: 172.16.23.131:9092,172.16.23.132:9092,172.16.23.133:9092
    group-id: TEST_ORG_CONSUMER_GROUP
liquibase:
  change-log: classpath:liquibase/master.xml
  default-schema: org_api_test
server:
  tomcat:
    accesslog:
      enabled: true
      directory: ~/Workspace/dinglicom/gateway_access_log
      pattern: '%h %l %u [%{yyyy-MM-dd HH:mm:ss.SSS}t] "%r" %s %b %D'
      prefix: org_api_access_log
      suffix: .log
    basedir: ~/Workspace/dinglicom/zhixin_API_Gateway_business/tmp/org_manager
logging.level.com.aizhixin.cloud: DEBUG

zookeeper:
  connecton: 172.16.23.131:2181
  path: /org/lock
  task: /org/task
kafka:
  nodes: 172.16.23.122:9092

zhixin.api.url: http://dledu.aizhixintest.com/zhixin_api
dd.api.url: http://dd.aizhixintest.com/diandian_api
period:
  mycj:
    orgId: 244
    week: 2

topic:
  class_teacher_add: TEST_CLASS_TEACHER_ADD
  teaching_class_add: TEST_TEACHING_CLASS_ADD
  teaching_class_update: TEST_TEACHING_CLASS_UPDATE
  teaching_class_delete: TEST_TEACHING_CLASS_DELETE
  teaching_class_teacher_add: TEST_TEACHING_CLASS_TEACHER_ADD
  teaching_class_teacher_delete: TEST_TEACHING_CLASS_TEACHER_DELETE
  teaching_class_student_add: TEST_TEACHING_CLASS_STUDENT_ADD
  teaching_class_student_delete: TEST_TEACHING_CLASS_STUDENT_DELETE
  teaching_class_user_delete_all: TEST_TEACHING_CLASS_USER_DELETE_ALL
  student_delete: TEST_STUDENT_DELETE
  data_syn: TEST_ORG_DATA_SYN_NEWTT
sys:
  role:
    group2m: M
    group2com: COM
    group2b: B
    group2c: C
    groupm:
      admin: ROLE_ADMIN
    groupb:
      student: ROLE_STUDENT
      teacher: ROLE_TEACHER
      orgadmin: ROLE_ORG_ADMIN
      orgmanager: ROLE_ORG_MANAGER
      collegeadmin: ROLE_COLLEGE_ADMIN
      classesadmin: ROLE_CLASSES_ADMIN
      orgdataview: ROLE_ORG_DATAVIEW
      collegedataview: ROLE_COLLEG_DATAVIEW
      orgeducationalmanager: ROLE_ORG_EDUCATIONALMANAGER
      collegeeducationalmanager: ROLE_COLLEG_EDUCATIONALMANAGER
      financeadmin: ROLE_FINANCE_ADMIN
      dormadmin: ROLE_DORM_ADMIN
      enroladmin: ROLE_ENROL_ADMIN
    groupcom:
      teacher: ROLE_COM_TEACHER
  version: v0.0.2.0