package com.aizhixin.cloud.orgmanager.common.core;

public interface DataSynType {
    String TEACHING_CLASS_ADD= "TEACHING_CLASS_ADD";
    String TEACHING_CLASS_UPDATE ="TEACHING_CLASS_UPDATE";
    String TEACHING_CLASS_DELETE= "TEACHING_CLASS_DELETE";
    String TEACHING_CLASS_TEACHER_ADD="TEACHING_CLASS_TEACHER_ADD";
    String TEACHING_CLASS_TEACHER_DELETE="TEACHING_CLASS_TEACHER_DELETE";
    String TEACHING_CLASS_STUDENT_ADD="TEACHING_CLASS_STUDENT_ADD";
    String TEACHING_CLASS_STUDENT_DELETE="TEACHING_CLASS_STUDENT_DELETE";
    String TEACHING_CLASS_USER_DELETE_ALL="TEACHING_CLASS_USER_DELETE_ALL";
    String STUDENT_DELETE="STUDENT_DELETE";
    String COURSE_UPDATE="COURSE_UPDATE";
}
