@startuml

管理员 --> (创建收费科目)
管理员 -> (查看收费科目对应的的人员及收费信息)
(按照收费科目导入人员信息) <- 管理员
管理员 --> (发布收费科目)
管理员 --> (导出收费科目对应的收费统计表)



/':Main Admin: as Admin
(Use the application) as (Use)

User -> (Start)
User --> (Use)

Admin ---> (Use)

note right of Admin : This is an example.

note right of (Use)
A note can also
be on several lines
end note

note "This note is connected\nto several objects." as N2
(Start) .. N2
N2 .. (Use)'/
@enduml