spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:59776;DatabaseName=kingo_jwgldb;
    username: sa
    password: admin
    hikari:
      auto-commit: false

logging.level.com.aizhixin.cloud: INFO

sys:
  version: v0.0.01