eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://172.16.23.120:1111/eureka/,http://172.16.23.121:1111/eureka/
spring:
  cloud:
    inetutils:
      ignored-interfaces: eth1
    config:
      server:
        git:
          uri: http://172.16.23.241/edu/zx-global-config.git
          search-paths: config-repo
          username: ZxRobot
          password: dinglicom.com
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
    stream:
      kafka:
        binder:
          zk-nodes: 172.16.23.131:2181,172.16.23.132:2181,172.16.23.133:2181
          brokers: 172.16.23.131:9092,172.16.23.132:9092,172.16.23.133:9092
server:
  tomcat:
    accesslog:
      enabled: true
      directory: /dinglicom/access_log
      pattern: '%h %l %u [%{yyyy-MM-dd HH:mm:ss.SSS}t] "%r" %s %b %D'
      prefix: config_access_log
      suffix: .log
    basedir: /dinglicom/tmp/config