eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://172.16.23.43:1111/eureka/,http://172.16.23.42:1111/eureka/
spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - eth1
        - em1
        - em3
        - em4
        - usb0
    config:
      server:
        git:
          uri: http://172.16.23.51:18002/aizhixin/cloud_config_server.git
          search-paths: config-repo
          username: messages@aizhixin.com
          password: dinglicom1qa2ws#ED
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
    stream:
      kafka:
        binder:
          zk-nodes: 172.16.23.43:2181,172.16.23.42:2181,172.16.23.51:2181
          brokers: 172.16.23.43:9092,172.16.23.42:9092,172.16.23.51:9092
server:
  tomcat:
    accesslog:
      enabled: true
      directory: /dinglicom/pay_access_log
      pattern: '%h %l %u [%{yyyy-MM-dd HH:mm:ss.SSS}t] "%r" %s %b %D'
      prefix: config_access_log
      suffix: .log
    basedir: /dinglicom/tmp/config